---
title: " "
pagetitle: "Research"
---
<p>&nbsp;</p>

# Working Papers
____________________________________________________________________________
### <u>Fertilization Impact Of Carbon Dioxide On Agricultural Yield</u>

There have been limited studies that identify the large-scale impact of atmospheric carbon dioxide on agricultural yield, especially for developing countries. I use NASA’s Orbiting Carbon Observatory – 2 (OCO-2) data to assess the impact of carbon dioxide on the yield of wheat, rice, and maize in India for 398 districts between the years 2014 to 2017. Using district level panel fixed effects model, I find that wheat yield increases by 0.8 percent with a 1 part per million (ppm) increase in atmospheric carbon dioxide. Rice yield declines by 1 percent for a 1 ppm increase in carbon dioxide, while there is no significant effect of carbon dioxide on maize. There is an endogeneity problem arising from the simultaneity of plants being a source of CO2 by respiring it out, which I overcome by controlling for vegetation in a region using the solar induced chlorophyll index (SIF). The decline in the rice yield with increased carbon dioxide in the atmosphere does not hold for the districts along the Indo-Gangetic plain, where the rice cultivars used are known to be superior to the rest of the country. I also test for the heterogeneity in the effect. For states that are leading in agriculture development in India (states with high GDP per capita and larger share of agriculture in GDP, Pingali 2017) I find that atmospheric carbon dioxide has no significant effect on agricultural yield across the three crops in these leading states, while there is a positive effect on wheat and maize yield for states that are lagging in agriculture growth. There is difference in the impact of carbon dioxide on yield based on water availability. There is no negative effect of atmospheric carbon dioxide on rice yield in districts without drought proneness.


### <u>Are Production And Consumption Decisions Independent? Identifying Separability In Indian Agriculture</u>

Production and consumption is said to follow separability when production decisions are made independent of consumption preferences. It has been explored in the past for agriculture households as it tends to breakdown for them due to the specific nature of their output, that these outputs can also be self consumed. Indian agriculture underwent major changes in terms of market access, input use and farm technology since the green revolution of the 1960s.There is limited research characterizing Indian agriculture recently, as the country is undergoing the process of structural transformation. In this paper I develop the theoretical model to test if farming households follow separability, extending the model by Dillon et al (2017). I show that household farm revenue is independent of household characteristics under separability. I then use this to test if farmers in Chandrapur district in the Indian state of Maharashtra follow separability, using a panel of 960 households for the years 2014 and 2016. I find that they fail to make production decisions independent of their consumption preferences as the household land and labor endowments positively impact the revenue received from crop sales. Under all specifications I use, land endowment is positively associated with the farm revenue from crop sales and, both land and labor endowments jointly affect farm revenue. For small and marginal land owning households, that is, less than 2.5 acres of land and for households that grow food crops, land and labor endowments, both individually and jointly affect farm revenue positively.




